# Generated by Django 4.1.7 on 2023-09-24 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_cartitem_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='user_photo',
            field=models.ImageField(blank=True, null=True, upload_to='user_photo/%Y/%m/%d/', verbose_name='Аватарка'),
        ),
    ]
