# Generated by Django 4.1.7 on 2023-09-14 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_users_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='photo',
        ),
    ]
