# Generated by Django 4.1.7 on 2023-09-18 08:53

from django.db import migrations, models
import django.db.models.deletion
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_users_birthday'),
    ]

    operations = [
        migrations.CreateModel(
            name='Characteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('characteristic_name', models.CharField(max_length=30, verbose_name='Название характеристки')),
                ('value', models.CharField(max_length=20, verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'Характеристика товара',
                'verbose_name_plural': 'Характеристи товаров',
            },
        ),
        migrations.CreateModel(
            name='Emails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
            ],
            options={
                'verbose_name': 'Неоправленное письмо',
                'verbose_name_plural': 'Неоправленные письма',
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer_name', models.CharField(max_length=100, unique=True, verbose_name='Наименование производителя')),
                ('country', models.CharField(blank=True, max_length=40, verbose_name='Страна')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL')),
                ('photo', models.ImageField(default='shop/static/img/favicon.svg', upload_to='img_category/%Y/%m/%d/', verbose_name='Фотография')),
            ],
            options={
                'verbose_name': 'Производитель',
                'verbose_name_plural': 'Производители',
            },
        ),
        migrations.CreateModel(
            name='Product_Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_name', models.CharField(blank=True, max_length=50, verbose_name='Картинка изображения')),
                ('img', models.ImageField(upload_to='img_product/%Y/%m/%d/', verbose_name='Изображение продукта')),
                ('first_img', models.BooleanField(default=False, verbose_name='Главная картинка')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Фотография продукта',
                'verbose_name_plural': 'Фотографии продуктов',
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.CreateModel(
            name='Discount_For_Product_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_percentage', models.FloatField(verbose_name='Скидка')),
                ('discount_start_date', models.DateField(auto_now_add=True, verbose_name='Начало скидок')),
                ('discount_end_date', models.DateField(verbose_name='Конец скидок')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL')),
                ('category_name', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='shop.category', verbose_name='Категория товаров')),
            ],
            options={
                'verbose_name': 'Скидка на категорию продукта',
                'verbose_name_plural': 'Скидки на категории продуктов',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.manufacturer', verbose_name='Производитель'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_characteristic',
            field=sortedm2m.fields.SortedManyToManyField(help_text=None, to='shop.characteristic', verbose_name='Характеристики'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_photos',
            field=sortedm2m.fields.SortedManyToManyField(help_text=None, to='shop.product_images', verbose_name='Изображения'),
        ),
    ]
